### ISSUE TITLE
Re-export isZodDto and ZodDto from the main entrypoint

### ISSUE THREAD

**Issue by sam-super** [BenLorantfy/nestjs-zod#431]
## Summary

`isZodDto` and `ZodDto` are only available from the `nestjs-zod/dto` subpath, and that subpath is awkward to consume under TypeScript's legacy `moduleResolution: "node"` (a.k.a. `node10`).
Ideally they would be re-exported from the main `nestjs-zod` entrypoint, alongside `createZodDto`

## Motivation

Projects with `module: "commonjs"` and no explicit `moduleResolution` (the TS 4.x default, still common in NestJS apps) fall back to `node10`, which does not read the `exports` map. 

For these projects:

```ts
import { isZodDto } from 'nestjs-zod/dto';
```

... fails at type-check time: `error TS2307: Cannot find module 'nestjs-zod/dto'`.

Runtime works fine — only TypeScript type resolution fails. The main entrypoint resolves correctly because v5 keeps a top-level `"types": "./dist/index.d.cts";` the subpath has no equivalent fallback.

Bumping moduleResolution is the principled long-term answer, but for many projects it's a non-trivial migration 

Ideally we would be able to do this:

```import { isZodDto, ZodDto } from 'nestjs-zod';```

(`createZodDto` is already re-exported this way)

FWIW this worked in v4.3.1's because the package.json included a root-level shim:
```  "files": ["dist", "logo.svg", "dto.d.ts"]```
... but in v5 `dto.d.ts` is gone.

## Versions

- nestjs-zod: 5.4.0
